"""add is_deleted to organizations

Revision ID: 601070ad770d
Revises: f840f3a512a6
Create Date: 2025-08-29 12:31:58.524036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601070ad770d'
down_revision: Union[str, Sequence[str], None] = 'f840f3a512a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_organizations_is_deleted'), 'organizations', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_is_deleted'), table_name='organizations')
    op.drop_column('organizations', 'is_deleted')
    # ### end Alembic commands ###
